version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: min-url-monolith
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./data:/app/data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    environment:
      - PORT=3000
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/db/sqlite.db
